### ISSUE TITLE
[Prototype] New UI

### ISSUE THREAD

**Issue by KaNaDaAT** [Local-Admin-BurgerKing/installer#5]
**General Info**
For the reason of the old UI beeing outdated we want to create a new one. There for we will need to test different technolegies and then use the best for a new design.

**Comment by nbrugger-tgm** [comment]
### Technologies to test
- [ ] BudiBase
- [ ] Angular
    - [ ] Bootstrap
    - [ ] Material
    - [ ] Clarity 
- [ ] Svelte

**Comment by nbrugger-tgm** [comment]
Depends on : https://github.com/Local-Admin-BurgerKing/core/issues/69

**Comment by KaNaDaAT** [comment]
Looked into Budibase and Appsmith. Non of these will work as we need it.

**Comment by nbrugger-tgm** [comment]
UI was implemented with 2 prototypes;
- Svelte + Bootstrap
- Angular + PrimeNG

While Svelte felt very pleasant to use, it being a young project and not having an extensive ecosystem excluded it from huge scale use. Also, that events/EventEmitters are not strictly typed + do not provide autocompletion didn't promote the idea of using svelte in production.

While angular has more boilerplate code, i am more familiar with it and PrimeNg offers great designs. Als Angular is inline with this projects technology stack: strict typing, compile time error detection, well established technologies

So Angular with PrimeNg as design framework will be used for the new UI

**Comment by nbrugger-tgm** [comment]
## Tasks

- [ ] Create seperate repository for the angular webpage
